---
apiVersion: v1
kind: Service
metadata:
  name: django-svc
  labels: 
    app: django
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: django
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
        env: test
    spec:
      containers:
      - name: django
        image: nexgtech/django
        ports:
        - containerPort: 8000
